tilt-dev/servantes

- .gitignore
- cmd/servantes/main.go
- web/servantes/templates/index.tpl
Hello @nicks,
Please review the following commits I made in branch nicks/servantes:
28f25390f3b58b1265814f882efd2296f9d172aa (2018-08-27 23:49:53 -0400)
servantes: make servantes a bit prettier
> servantes: make servantes a bit prettier

- cmd/servantes/main.go
Hello @nicks,
Please review the following commits I made in branch nicks/err:
ed37bcc44266d328526754d59d4974387ca58b1c (2018-08-28 11:55:52 -0400)
servantes: fail gracefully if k8s api fails
> servantes: fail gracefully if k8s api fails

- deployments/servantes/servantes.yaml
Hello @nicks,
Please review the following commits I made in branch nicks/rbac:
8564a428eb4a2cc659934c223f454173523c3349 (2018-08-28 11:59:04 -0400)
servantes: add rbac roles
> servantes: add rbac roles

- Tiltfile
Hello @nicks,
Please review the following commits I made in branch nicks/sub2:
27ba6895ee184073f6af8147e4f7633d2ae4e07d (2018-08-28 12:43:19 -0400)
Tiltfile: each service should only mount what they need
> Tiltfile: each service should only mount what they need

- Tiltfile
- doggos/deployments/doggos.yaml
- doggos/main.go
- doggos/web/templates/index.tpl
- fortune/web/templates/index.tpl
- servantes/main.go
- servantes/web/templates/index.tpl
Hello @nicks,
Please review the following commits I made in branch nicks/tweets:
8a65af670c74facf2c8333acea325df9762d5f10 (2018-08-29 17:31:58 -0400)
Add a doggos service, and tweak the output a bit
> Add a doggos service, and tweak the output a bit

- servantes/main.go
Hello @nicks,
Please review the following commits I made in branch nicks/timing:
b0d44b7a86ad7a95683e1890c3bc5e2dcd8c73d0 (2018-09-05 17:53:28 -0400)
servantes: reflect the container age rather than the pod age
> servantes: reflect the container age rather than the pod age

- Tiltfile
- doggos/deployments/doggos.yaml
- fortune/deployments/fortune.yaml
- hypothesizer/deployments/hypothesizer.yaml
- servantes/deployments/servantes.yaml
- snack/deployments/snack.yaml
- spoonerisms/deployments/spoonerisms.yaml
- vigoda/deployments/vigoda.yaml
> servantes: use gcr.io image tags

- Tiltfile
Hello @jazzdan,
Please review the following commits I made in branch nicks/yarn:
4226e702cfa4a1c5043f3f99b4bc0828c31c29c3 (2018-09-12 14:35:00 -0400)
add conditional runs to the tiltfile
> add conditional runs to the tiltfile

- Tiltfile
per discussion here https://app.clubhouse.io/windmill/story/309/servantes-tiltfile-should-repeat-itself
> tiltfile is WET: write everything twice

- fortune/web/templates/index.tpl
- servantes/web/templates/index.tpl
- snack/web/templates/index.tpl
- vigoda/deployments/vigoda.yaml
- vigoda/main.go
- vigoda/web/templates/index.tpl
More typographic fun with our widgets.
Apologies for a weird commit history — I messed something up in my Gitting haste.
> style: widget ui

- Tiltfile
- emoji/deployments/emoji.yaml
- emoji/main.go
- emoji/pkg/emoji/emoji.go
- emoji/web/templates/index.tpl
- fe/main.go
This simply displays a handful of random emoji, e.g.:
> servantes: add emoji service

- fe/main.go
Hello @landism, @maiamcc,
Please review the following commits I made in branch nicks/segfault:
6756dbaeb7b55cdbdc27de85209c0bad08c080ca (2018-09-28 14:24:34 -0400)
fe: fix a segfault if the pod isn't up
> fe: fix a segfault if the pod isn't up

- .dockerignore
- doggos/deployments/doggos.yaml
- emoji/deployments/emoji.yaml
- fe/deployments/fe.yaml
- fortune/deployments/fortune.yaml
- hypothesizer/deployments/hypothesizer.yaml
- snack/deployments/snack.yaml
- spoonerisms/deployments/spoonerisms.yaml
- vigoda/deployments/vigoda.yaml
Hello @nicks,
Please review the following commits I made in branch nicks/deployment:
0d50b00c70e2f8299d8733d279bd19b08e2df04d (2018-10-08 13:14:51 -0400)
upgrade all deployments to v1
> upgrade all deployments to v1

- .gitignore
we should fix this bug for real but in the meantime this was throwing
too many errors for me to actually write other code -_-
> git: add goalnd tempfiles to gitignore so maia and matt can develop in peace

- Tiltfile
Hello @jazzdan, @nicks,
Please review the following commits I made in branch maiamcc/yaml-optional-arg:
fc0c33c8fc2233f965d861af3d1822aa76e12069 (2018-11-02 16:31:34 -0400)
tiltfile: new k8s_service syntax
> tiltfile: new k8s_service syntax

- Tiltfile
- doggos/deployments/doggos.yaml
- emoji/deployments/emoji.yaml
- fortune/deployments/fortune.yaml
- snack/deployments/snack.yaml
- spoonerisms/deployments/spoonerisms.yaml
- vigoda/deployments/vigoda.yaml
- words/deployments/words.yaml
Hello @maiamcc,
Please review the following commits I made in branch nicks/services:
fa936f060d639a22f1e3ad13ab8769cee6530903 (2018-11-09 16:14:30 -0500)
remove unnecessary services
> remove unnecessary services

- Tiltfile
- Tiltfile.dc
Blocked on https://github.com/windmilleng/tilt/pull/913
> Split k8s Tiltfile and docker compose Tiltfile

- Tiltfile.dc
- docker-compose.yml
Hello @jazzdan, @landism,
Please review the following commits I made in branch dc-fastbuild:
90a3575fbdc8c28d67306bd1d201d1877f101ed7 (2019-02-02 14:11:37 -0500)
fastbuild for docker compose
> fastbuild for docker compose

- Tiltfile
make Tiltfile compatible with syntax change in [PR #1191](https://github.com/windmilleng/tilt/pull/1191)
> update tiltfile with yaml typing

- Tiltfile
This reverts commit 0597602c2c6387bbda6216638ba6b97bcf035a7c.
> Revert "update tiltfile with yaml typing (#77)"

- Tiltfile
- deploy/hello_world.yaml
Hello @jazzdan, @landism,
Please review the following commits I made in branch maiamcc/out-of-box-3rdparty:
b17ef84cbe3a457cd315223c1aa0d5df2f9a9d6a (2019-02-22 16:17:34 -0500)
simpler out-of-the-box (i.e. unbuilt) service example
> simpler out-of-the-box (i.e. unbuilt) service example

- Tiltfile
- deploy/tick.yaml
To expose that Cron Jobs behave kind of weirdly in Tilt right now.
> Add a CronJob

- Tiltfile
Hello @jazzdan, @dbentley,
Please review the following commits I made in branch maiamcc/username_var:
63ce7219275b12970ae7be8b1b97790471b88845 (2019-02-21 12:40:44 -0500)
clean up tiltfile by replacing get_username() func w/ username var
> clean up tiltfile by replacing get_username() func w/ username var

- Tiltfile
(demonstrating https://github.com/windmilleng/tilt/pull/1317)
> spoonerisms uses staticBuild PLUS fastBuild

- Tiltfile.dc
Hello @nicks,
Please review the following commits I made in branch maiamcc/tiltfile-dc-live-update:
2dcd862740269da1a1f5e0d4fb703f1f2b98bdf6 (2019-07-05 11:58:33 -0400)
update tiltfile.dc to use correct live_update syntax
> update tiltfile.dc to use correct live_update syntax

- Tiltfile
Hello @jazzdan, @nicks,
Please review the following commits I made in branch maiamcc/live-update-multi-c:
434e44b25c88a404dee468411327dc635c1a9736 (2019-08-09 09:56:56 -0400)
live update both doggos and its sidecar
> live update both doggos and its sidecar

- doggos/main.go
- emoji/main.go
- fe/main.go
- fortune/main.go
- secrets/main.go
- snack/main.go
- vigoda/main.go
ListenAndServe was failing silently when running locally and the port was in use
> servantes: log ListenAndServe errors

- .gitignore
- Tiltfile
- tilt_modules/extensions.json
- tilt_modules/restart_process/Tiltfile
use [restart_process extension](https://github.com/windmilleng/tilt-extensions/tree/master/restart_process) instead of restart_container (as part of dogfooding the extension)
> restart_process extension instead of restart_container

- README.md
Hello @nicks,
Please review the following commits I made in branch nicks/ci:
a8102dd454d29aa116773061f3727fdced02dab8 (2021-03-30 16:19:24 -0400)
readme: add ci badge
> readme: add ci badge

- tilt_modules/extensions.json
- tilt_modules/restart_process/.gitignore
- tilt_modules/restart_process/Dockerfile
- tilt_modules/restart_process/README.md
- tilt_modules/restart_process/Tiltfile
- tilt_modules/restart_process/release.sh
- tilt_modules/restart_process/test/Dockerfile
- tilt_modules/restart_process/test/Tiltfile
- tilt_modules/restart_process/test/custom.Tiltfile
- tilt_modules/restart_process/test/fail.sh
- tilt_modules/restart_process/test/job.yaml
- tilt_modules/restart_process/test/test-custom.sh
- tilt_modules/restart_process/test/test-docker.sh
- tilt_modules/restart_process/test/test.sh
- tilt_modules/restart_process/tilt-restart-wrapper.go
Hello @landism,
Please review the following commits I made in branch maiamcc/bump-restart-process:
07bc0efa8ddaa719c430bbcd574026a0cb2f253e (2021-04-30 13:36:39 -0400)
bump restart process ext
> bump restart process ext
